Add warning message on incomplete tests too
nunomaduro/collision pull request #110
Opened 2020-04-08 11:29 UTC by mathieutu

Hi @nunomaduro,
The warning message was not passed for incomplete tests, like it is for risky and skipped ones.

This is done.

2020-04-08 12:10 UTC, nunomaduro requested changes
Can you add/adjust the tests on this? If is too much work I can do it for you.

2020-04-08 12:51 UTC, mathieutu commented
Actually, I've just been lazy on that, and made the PR quickly directly on Github without cloning it. I could do it later if you want (or do it on your side if you're in the code before me, no matter for me).

But btw, nothing is failing here... No CI for tests on this project?! Come on @nunomaduro 😛!

2020-04-08 12:53 UTC, nunomaduro commented
I will add a test later on this. No worries.

2020-04-08 12:54 UTC, nunomaduro commented
We have CI tests on this project, no sure why they are not showing up on this pull request.

2020-04-08 12:56 UTC, nunomaduro commented
https://travis-ci.org/github/nunomaduro/collision

2020-04-18 17:58 UTC, nunomaduro commented
Thanks men! It's fixed here: https://github.com/nunomaduro/collision/commit/a442e05867fe13c9cd114b7d2b212e3999d0dd88.

2020-04-18 17:58 UTC, closed without merging