Makes Collision 5 supports only Laravel 8
nunomaduro/collision pull request #126
Opened 2020-06-18 21:40 UTC by nunomaduro

cc @GrahamCampbell

2020-06-18 21:45 UTC, GrahamCampbell commented
// cc @taylorotwell this will break the laravel/laravel develop branch?

2020-06-18 21:46 UTC, nunomaduro commented
@GrahamCampbell I will test it.

2020-06-18 21:53 UTC, GrahamCampbell requested changes

2020-06-18 21:53 UTC, GrahamCampbell commented on composer.json
> +        "laravel/framework": "<8.0"
Just below require dev asks for 7?

2020-06-18 22:31 UTC, nunomaduro commented on composer.json
> +        "laravel/framework": "<8.0"
That will change.

2020-06-22 00:03 UTC, nunomaduro commented
Done here: https://github.com/nunomaduro/collision/commit/ba26119149a7e42fbace9c09584596d313a535fd. Collision 5 artisan test command requires laravel 8.

2020-06-22 00:03 UTC, closed without merging