Emit output with beStrictAboutOutputDuringTests=false in Phpunit/Printer
nunomaduro/collision pull request #130
Opened 2020-06-20 03:05 UTC by nobuf

Coming from pest https://github.com/pestphp/pest/issues/73

While PHPUnit's DefaultResultPrinter emits output to stdout anyways if beStrictAboutOutputDuringTests sets false, collision might want to follow the same behavior.

2020-06-22 00:32 UTC, nunomaduro commented
@nobuf can you rebase ?

2020-06-22 12:18 UTC, nobuf commented
OK, done!

2020-07-08 12:31 UTC, toonvandenbos requested changes
I can confirm this PR solves [my issue](https://twitter.com/nyratas/status/1280553603837702144), however it seems to break 2 tests in `tests/Unit/WriterTest.php`.

I do not have enough knowledge about this particular package to help you solve these issues, but it appears they both concern the output format:

`Tests\Unit\WriterTest > it writes the exception`
```
  Failed asserting that two strings are equal.

  at tests/Unit/WriterTest.php:76
     72▕ 
     73▕ EOF;
     74▕ 
     75▕         $this->assertEquals(
  ➜  76▕             $writer->getOutput()
     77▕                 ->fetch(),
     78▕             $result
     79▕         );
     80▕     }
  --- Expected
  +++ Actual
  @@ @@
        12▕     }\n
        13▕ }\n
        14▕\n
  +\n
  +  1   tests/FakeProgram/HelloWorldFile2.php:11\n
  +      Tests\FakeProgram\HelloWorldFile3::say()\n
  +\n
  +  2   tests/FakeProgram/HelloWorldFile1.php:11\n
  +      Tests\FakeProgram\HelloWorldFile2::say()\n
   '
```

`Tests\Unit\WriterTest > it hides editor`
```
  Failed asserting that '\n
     Tests\FakeProgram\FakeException \n
  \n
    Fail description\n
  ' contains "
     Tests\FakeProgram\FakeException 
  
    Fail description
  
    1   tests/FakeProgram/HelloWorldFile2.php:11
        Tests\FakeProgram\HelloWorldFile3::say()
  
    2   tests/FakeProgram/HelloWorldFile1.php:11
        Tests\FakeProgram\HelloWorldFile2::say()".

  at tests/Unit/WriterTest.php:169
    165▕ 
    166▕         $this->assertStringContainsString(
    167▕             $result,
    168▕             $writer->getOutput()
  ➜ 169▕                 ->fetch()
    170▕         );
    171▕     }
    172▕ 
    173▕     /** @test */
```

Maybe these issues are false negatives due to my local setup, in which case I apologize and hope it gets merged soon :)

2020-07-09 15:28 UTC, Nyratas commented
Update : this PR seems to add unwanted line-breaks to PestPHP's output.  

![image](https://user-images.githubusercontent.com/5635557/87059357-8039fe80-c209-11ea-848f-d3a9e0338400.png)

2020-07-09 15:33 UTC, nunomaduro commented
@nobuf Can you check this last issue?

2020-07-10 07:57 UTC, nobuf commented
@Nyratas Can you make a minimal, reproducible example? I believe ForwardsToMoneyTest is not a class in Collision. Also, I would like to see the output with beStrictAboutOutputDuringTests=true. Thanks!

2020-07-10 09:36 UTC, Nyratas commented
Hi @nobuf,

The example in the screenshot above is from a project I'm working on, the class names are unrelated to this issue. To reproduce the example above you could do the following :

1. Initialize a dummy PHP project including PestPHP (take a look at the [setup docs](https://pestphp.com/docs/installation/) if you're not familiar with it). The PestPHP dependency (also by @nunomaduro) will automatically require this package.
2. Replace `vendor/nunomaduro/collision` with the version from this PR
3. Update the project's `phpunit.xml` as needed (in my case I had `beStrictAboutOutputDuringTests="false"`)
4. Write some dummy PestPHP tests (just a few `it('tests something')->assertTrue(true)` will do)
5. Launch the tests using `./vendor/bin/pest`

In my experience the amount of empty line-breaks above each "section" is related to the number of tests in each file (each "section").

With  `beStrictAboutOutputDuringTests="true"` the output format is correct, but printing data from the tests (using `echo` and/or `var_dump`) is not possible anymore:

![image](https://user-images.githubusercontent.com/5635557/87140116-43b9e180-c2a1-11ea-9505-0c5ed3c2bea5.png)

2020-07-10 13:31 UTC, nobuf commented
Thanks for the steps! I've added a test case that confirms an extra line break. It should be fixed now at https://github.com/nunomaduro/collision/pull/130/commits/fdd84e4fcbab28dc7619f5d9e59450e664d9f3f9.

2020-07-18 17:12 UTC, nunomaduro commented
@nobuf can you rebase?

2020-07-20 14:09 UTC, nobuf commented
"Run Rector" is failing on CI and my local. It fails at 834a201a4866a70a06eeef29730c7ba1c9da4b2e the current stable branch as well.

The recently released phpstan [0.12.33](https://github.com/phpstan/phpstan-src/releases/tag/0.12.33) might be causing the issue. With 0.12.32, rector runs without an error.

With debug option:
```
vendor/bin/rector process src --dry-run --debug
...
Rector v0.7.48
Config file: rector.yaml

...
[parsing] src/Adapters/Phpunit/Printer.php
PHP Fatal error:  Uncaught PHPStan\ShouldNotHappenException: Internal error. in phar:///Users/nobu/projects/collision/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/ScopeContext.php:32
Stack trace:
#0 phar:///Users/nobu/projects/collision/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1540): PHPStan\Analyser\ScopeContext->enterClass(Object(PHPStan\Reflection\ClassReflection))
#1 /Users/nobu/projects/collision/vendor/rector/rector/packages/node-type-resolver/src/PHPStan/Scope/PHPStanNodeScopeResolver.php(189): PHPStan\Analyser\MutatingScope->enterClass(Object(PHPStan\Reflection\ClassReflection))
#2 /Users/nobu/projects/collision/vendor/rector/rector/packages/node-type-resolver/src/PHPStan/Scope/PHPStanNodeScopeResolver.php(133): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->resolveClassOrInterfaceScope(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope))
#3 phar:///Users/nobu/projects/collision/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(4 in phar:///Users/nobu/projects/collision/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/ScopeContext.php on line 32
```

2020-08-09 11:03 UTC, nunomaduro commented
@nobuf Can you rebase? That problem should be fixed.

2020-08-09 17:09 UTC, nunomaduro approved these changes
Thank you!

2020-08-09 17:10 UTC, merged