Add psalm as a dev dependency
nunomaduro/collision pull request #86
Opened 2020-01-31 20:01 UTC by NicolasCARPi

Rebased as per https://github.com/nunomaduro/collision/pull/84#issuecomment-579018368

2020-01-31 21:27 UTC, nunomaduro commented
@NicolasCARPi Thanks, can you also add it to the composer test script?

2020-01-31 22:00 UTC, nunomaduro commented
I will do it.

2020-02-01 00:02 UTC, NicolasCARPi commented
> can you also add it to the composer test script?

Added. `test:static` sounds like a good name to me :)

2020-02-01 00:59 UTC, nunomaduro commented on composer.json
> +        "test:static": "psalm",
Maybe test:types should call `phpstan analyse --ansi && psalm`.

2020-02-01 00:59 UTC, nunomaduro requested changes
Maybe test:types should call `phpstan analyse --ansi && psalm`.

2020-02-01 11:21 UTC, NicolasCARPi commented
Modified!

2020-02-19 14:59 UTC, nunomaduro commented
@NicolasCARPi can you fix tests.

2020-02-19 17:56 UTC, NicolasCARPi commented
@nunomaduro Not really no. The errors reported by psalm require careful consideration. I am not familiar enough with the codebase to address all these changes. This PR is only about adding psalm to the project so it can be run easily by a dev, as a first step before fixing the issues reported.

I would suggest disabling it from CI until all issues have been resolved. Once it is not throwing any error, enable it again in CI so PRs will get checked automagically.

2020-04-04 20:23 UTC, nunomaduro commented
Let's delay this.

2020-04-04 20:23 UTC, closed without merging